version: '3.3'

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-gs-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: comp3612021
    ports:
      - "3456:3306"
  
  backend:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile-ls-nest 
    ports:
      - "3454:3000"
      - "3455:3001"
    restart: unless-stopped
    depends_on: 
      - db