version: '3.3'

services:
  # db:
    # container_name: backend-db
    # image: mysql:5.7
    # restart: always
    # environment:
    #   MYSQL_DATABASE: 'elfenroad'
    #   MYSQL_USER: 'comp361'
    #   MYSQL_PASSWORD: 'elfenroad'
    #   MYSQL_ROOT_PASSWORD: 'elfenroads'
    # ports:
    #   - '3306:3306'
    # command: [--explicit_defaults_for_timestamp,--ignore-db-dir=lost+found] 
  
  backend:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile-ls-nest 
    ports:
      - "3454:3000"
      - "3455:3001"
    depends_on:
      - db
    restart: unless-stopped