name: Run clang-format

on: [push, pull_request]

jobs:
  clang_format:
    name: Run clang-format

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-format
      run: |
        sudo apt install clang-format-12
        alias clang-format=clang-format-12
        clang-format --version
    - name: Run clang-format
      run: |
        sh clang-format.sh diff
  
  npm:
    name: Run npm install
    
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      run: |
        sudo apt install nodejs
    
    - name: Run npm install
      run: |
        cd Elfenroads
        npm install
